config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats, only: [:new, :index, :create, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  validates :check_in_date, :check_out_date, presence: true
  validate :user_cannot_book_own_flat

  def user_cannot_book_own_flat
    errors.add(:base, "User cannot book their own flat") if user.id == flat&.user_id
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings
  belongs_to :user
  validates :address, :price, :guest, :flat_type, presence: true
  has_many_attached :photos
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :flat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :flats
  validates :first_name, :last_name, :is_host, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :is_host])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :is_host])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat
    if @booking.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @flat = current_user.flats if current_user.is_host
    @bookings = current_user.bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in_date, :check_out_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params.present?
      @flats = Flat.where(final_query(params))
    else
      @flats = Flat.all
    end
  end

  def search
  end

  def new
    @flat = Flat.new
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    if @flat.save
      redirect_to flats_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def flat_params
    params.require(:flat).permit(:address, :price, :guest, :flat_type, photos: [])
  end

  def final_query(params)
    query_conditions = []
    if params[:address].present?
      query_conditions << "address ILIKE '%#{params[:address]}%'"
    end
    if params[:guest].present?
      query_conditions << "guest ILIKE '%#{params[:guest]}%'"
    end
    query_conditions.join(' AND ')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container">
  <%= link_to "All Listing", flats_path %>
  <h1 >My flats bookings</h1>
  <% @flat.each do |flat| %>
    <% flat.bookings.each do |booking| %>
      <p><%= "Customer Name: #{booking.user.first_name} #{booking.user.last_name}"%></p>
      <p><%= "Address: #{flat.address}"%></p>
      <p><%= "Check-in Date: #{booking.check_in_date}"%></p>
      <p><%= "Check-out Date: #{booking.check_out_date}"%></p>
    <% end %>
  <% end %>
  <p><%= "You do not have any booking yet" if @flat.count == 0 %></p>
</div>

<div class="container">
  <h2>My Reservations</h2>
  <% @bookings.each do |booking| %>
      <p><%= "Address: #{booking.flat.address}"%></p>
      <p><%= "Check-in Date: #{booking.check_in_date}"%></p>
      <p><%= "Check-out Date: #{booking.check_out_date}"%></p>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="container">
<h1>Create a booking</h1>
<% if @booking.errors[:base].any? %>
  <% error_type = @booking.errors[:base].first %>
  <p><%= "Error Type: #{error_type}" %></p>
<% end %>
<%= link_to "Back to Flat", flat_path(@flat) %>
  <%= simple_form_for([@flat, @booking]) do |f| %>
    <%= f.input :check_in_date %>
    <%= f.input :check_out_date %>
    <%= f.submit %>
  <% end %>
</div>

app/views/flats/index.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <div class="card-container">
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat) do %>
        <div class="flat_card">
          <%= cl_image_tag flat.photos.last.key, height: 300, width: 400, class: "flat_card flat_card--img" if flat.photos.attached? %>
          <div>
            <div class="flat_card card-listing">
              <div>
                <p class="flat_card flat_card--title"><%= flat.address%></p>
                <p class="card-listing-subtitle">Professional Host</p>
                <p class="card-listing-subtitle">31 Oct - 5 Nov</p>
                <p class="card-listing-total">$727 total</p>
              </div>
              <div class="listing-review">
              <p >⭐ 4.93</p>
            </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <%= link_to "All Listing", flats_path %>
  <h1>Add a new flat</h1>
  <%= render 'shared/form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <%= link_to "Book flat", new_flat_booking_path(@flat) %>
  <%= @flat.address %>
  <%= link_to "All flat", flats_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbTask</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for(flat) do |f| %>
    <%= f.input :address %>
    <%= f.input :price %>
    <%= f.input :guest %>
    <%= f.input :flat_type %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="container ">
  <nav class="navbar ">
    <h1 class="navbar-logo">airbnb</h1>
    <div class="navbar-navigation">
      <p class="navbar-navigation-item">Stays</p>
      <p class="navbar-navigation-item">Experiences</p>
      <p class="navbar-navigation-item">Online Experiences</p>
    </div>
    <div class="navbar-navigation">
      <p ><%= link_to "Airbnb your home", new_flat_path if current_user.is_host %></p>
    </div>
  </nav>
  <div class="search-field">
    <%= form_tag(flats_path, method: :get, class: 'search-form') do %>
      <%= label_tag :address, "Where", class: "address-label" %>
      <%= text_field_tag :address, params[:address], placeholder: "Search destinations", class: "navbar-search" %>
      <%= label_tag :guest, "Guest" , class: "guest-label"%>
      <%= text_field_tag :guest, params[:guest], placeholder: "Search destinations", class: "navbar-search" %>
      <%= submit_tag "Search", class: "search-form__submitbtn" %>
    <% end %>
  </div>
<hr>
</div>